services:
  - type: web
    name: task-manager-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_INVITE_TOKEN
        sync: false
      - key: PORT
        value: "8000"
      - key: CLIENT_URL
        sync: false
